# -*- coding: utf-8 -*-
"""CNN Architecture

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r-fYUvt7x-UuV10Ji4eqDFVhkkHs6jRS
"""

# Step 1: Import Libraries
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt

# Step 2: Load Dataset
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Step 3: Preprocessing
x_train = x_train / 255.0
x_test = x_test / 255.0

# Reshape for CNN (Add channel dimension)
x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)

# Step 4: Build CNN Model
model = keras.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(10, activation='softmax')
])

# Step 5: Compile Model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Step 6: Train Model
history = model.fit(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

# Step 7: Evaluate Model
test_loss, test_acc = model.evaluate(x_test, y_test)
print("Test Accuracy:", test_acc)

# Step 8: Prediction Example
import numpy as np

plt.imshow(x_test[0].reshape(28,28), cmap='gray')
plt.title("Actual Label: " + str(y_test[0]))
plt.show()

prediction = model.predict(x_test[0].reshape(1,28,28,1))
print("Predicted Label:", np.argmax(prediction))